CreateAtGlobal = 2015-09-06T04:01:52Z

[[LabelSeverityWeight]]
LabelName = "severity/critical"
Weight = 10.0

[[LabelSeverityWeight]]
LabelName = "severity/major"
Weight = 3.0

[[LabelSeverityWeight]]
LabelName = "severity/moderate"
Weight = 1.0

[[LabelSeverityWeight]]
LabelName = "severity/minor"
Weight = 0.1

[[RepositoryArgs]]
Owner = "tikv"
Name = "tikv"

[[RepositoryArgs]]
Owner = "tikv"
Name = "pd"

[[RepositoryArgs]]
Owner = "pingcap"
Name = "tidb"

[[RepositoryArgs]]
Owner = "pingcap"
Name = "dm"

[[RepositoryArgs]]
Owner = "pingcap"
Name = "ticdc"

[[RepositoryArgs]]
Owner = "pingcap"
Name = "br"

[[RepositoryArgs]]
Owner = "pingcap"
Name = "tidb-lightning"

[[RepositoryArgs]]
Owner = "pingcap"
Name = "tidb-operator"

[[RepositoryArgs]]
Owner = "pingcap"
Name = "tiup"

[CrawlerConfig]
GraphqlPath = "./infrastructure/github/crawler/graphql/query.graphql"
ServerUrl = "https://api.github.com/graphql"
Authorization = []

[DatabaseConfig]
DatabaseUrl = ""

[[TeamArgs]]
Name = "Runtime"
Size = 7

[[TeamArgs]]
Name = "Optimizer"
Size = 7

[[TeamArgs]]
Name = "Transaction-A Transaction-B"
Size = 11

[[TeamArgs]]
Name = "General"
Size = 9

[[TeamArgs]]
Name = "TP-Storage Cloud-Storage"
Size = 15

[[TeamArgs]]
Name = "Scheduling"
Size = 9